apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - api-despachos-deployment.yaml
  - api-despachos-service.yaml
  - api-ventas-deployment.yaml
  - api-ventas-service.yaml
  - ingress.yaml
  - hpa.yaml
