apiVersion: v1
kind: Secret
metadata:
  name: innovatech-db-secret
  namespace: innovatech
  labels:
    app.kubernetes.io/name: innovatech-logistics
    app.kubernetes.io/part-of: innovatech-logistics-platform
type: Opaque
stringData:
  DB_USERNAME: "innovatech_user"
  DB_PASSWORD: "change-me"

